name: Continous Deployment
on: 
  workflow_dispatch:
  push:
#     branches: [ main ]
#     # Publish semver tags as releases.
    tags: 
      - "dev-*"
#   pull_request:
#     branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG_IMAGE: ghcr.io/lintasarta/test:${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
        - name: Print Value Pada Deploy
          run: echo ${{ env.TAG_IMAGE }}
